[integration.mqtt.auth.generic]
servers=["tcp://172.17.0.1:1883"]
username="interface"
password="9fgtykj"

[integration.mqtt]
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/#"